# Generated by Django 3.2.4 on 2022-05-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('communication_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Score')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_communication', to='communications.communication')),
                ('communication_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_communication_field', to='communication_fields.communicationfield')),
            ],
            options={
                'db_table': 'CommunicationScore',
            },
        ),
    ]
