# Generated by Django 3.2.4 on 2022-05-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberleave',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('req_modification', 'Request Modification'), ('forwarded', 'Forwarded'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=50, verbose_name='Leave Status'),
        ),
    ]
