# Generated by Django 3.2.4 on 2022-12-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_leaves', '0002_alter_memberleave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberleave',
            name='status',
            field=models.CharField(choices=[('n/a', 'N/A'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='applied', max_length=50, verbose_name='Leave Status'),
        ),
    ]
