# Generated by Django 3.2.4 on 2022-07-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20220707_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='target_created_by',
            new_name='created_by',
        ),
    ]
