# Generated by Django 3.2.4 on 2022-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_rename_target_created_by_target_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
    ]
