# Generated by Django 3.2.4 on 2022-07-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(choices=[('n/a', 'N/A'), ('batch1', 'Batch1'), ('batch2', 'Batch2'), ('batch3', 'Batch3'), ('batch4', 'Batch4'), ('batch5', 'Batch5')], default='N/A', max_length=50, verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(choices=[('n/a', 'N/A'), ('day', 'Day'), ('night', 'Night')], default='N/A', max_length=50, verbose_name='Shift'),
        ),
    ]
