# Generated by Django 3.2.4 on 2022-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220707_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shift',
        ),
        migrations.AddField(
            model_name='user',
            name='shifts',
            field=models.CharField(choices=[('n/a', 'N/A'), ('day', 'Day'), ('night', 'Night')], default='N/A', max_length=50, verbose_name='Shifts'),
        ),
    ]
