# Generated by Django 3.2.4 on 2022-07-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    def blank_to_zero(apps, schema_editor):
        user_model = apps.get_model('users', 'User')

        for obj in user_model.objects.filter(employee_id=''):
            obj.employee_id = 0
            obj.save()

    dependencies = [
        ('users', '0003_auto_20220713_1323'),
    ]

    operations = [
        migrations.RunPython(blank_to_zero),
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(choices=[('n/a', 'N/A'), ('batch1', 'Batch1'), ('batch2', 'Batch2'), ('batch3', 'Batch3'), ('batch4', 'Batch4'), ('batch5', 'Batch5'), ('under_training', 'Under Training')], default='N/A', max_length=50, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Employee ID'),
        ),
    ]
