# Generated by Django 3.2.4 on 2022-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220715_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shifts',
            field=models.CharField(choices=[('n/a', 'N/A'), ('day', 'Day'), ('night', 'Night'), ('afternoon', 'Afternoon')], default='N/A', max_length=50, verbose_name='Shifts'),
        ),
    ]
