# Generated by Django 3.2.4 on 2022-09-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220823_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(choices=[('n/a', 'N/A'), ('batch1', 'Batch1'), ('batch2', 'Batch2'), ('batch3', 'Batch3'), ('batch4', 'Batch4'), ('batch5', 'Batch5'), ('batch6', 'Batch6'), ('batch7', 'Batch7'), ('batch8', 'Batch8'), ('under_training', 'Under Training')], default='N/A', max_length=50, verbose_name='Batch'),
        ),
    ]
