# Generated by Django 3.2.4 on 2022-05-31 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_leaves', '0001_initial'),
        ('leave_conversations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveconversation',
            name='message',
        ),
        migrations.AddField(
            model_name='leaveconversation',
            name='message_body',
            field=models.TextField(default='Add your Comment', verbose_name='Text Message'),
        ),
        migrations.AlterField(
            model_name='leaveconversation',
            name='member_leave_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='member_leaves.memberleave'),
        ),
    ]
