# Generated by Django 3.2.4 on 2022-07-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220707_1444'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Taskname'),
        ),
        migrations.AlterField(
            model_name='task',
            name='session_video_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Session video link'),
        ),
        migrations.AlterField(
            model_name='task',
            name='student_support_type',
            field=models.CharField(choices=[('hackerrank', 'Hackerrank'), ('ec', 'EC'), ('cohort', 'Cohort'), ('pair_programming', 'Pair Programming'), ('doubt', 'Doubt'), ('quiz', 'Quiz'), ('group_development', 'Group Development'), ('self_development', 'Self Development'), ('brainstroming', 'Brainstroming'), ('beniten_team', 'Beniten Team'), ('missing_students', 'Missing Students'), ('training', 'Training'), ('assignment_check', 'Assignment Check'), ('review', 'Team Review'), ('meeting', 'Meeting'), ('project', 'Project Support'), ('job_support', 'Job Support'), ('internal_task', 'Internal Task'), ('internal_project', 'Internal Project')], max_length=200, verbose_name='Student Support type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('student_support', 'Student Support'), ('meeting', 'Internal Team Meeting'), ('studying', 'Studying'), ('project', 'Project(Client Project, Internal Project)'), ('internal_support', 'Internal Support'), ('internal_project', 'Internal Project')], max_length=50, verbose_name='Type'),
        ),
    ]
