# Generated by Django 3.2.4 on 2022-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('critical', 'Critical'), ('general', 'General'), ('error', 'Error')], max_length=50, verbose_name='Communication Type')),
                ('attribute_of_communication', models.CharField(max_length=255, verbose_name='Attribute Of Communication')),
            ],
            options={
                'db_table': 'CommunicationField',
            },
        ),
    ]
