# Generated by Django 4.1.4 on 2022-12-20 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('n/a', 'N/A'), ('casual_leave', 'Casual Leave'), ('sick_leave', 'Sick Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Leave'), ('loss_of_pay_leave', 'Loss of Pay Leave'), ('emergency', 'Emergency Leave')], default='N/A', max_length=50, verbose_name='Leave Type')),
                ('leave_balance', models.IntegerField(default=0, verbose_name='Leave Balance')),
                ('from_date', models.DateTimeField(verbose_name='From Date')),
                ('to_date', models.DateTimeField(verbose_name='To Date')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('applied_to', models.CharField(choices=[('saravana_kumar', 'Saravana Kumar'), ('rajeshwari', 'Rajeshwari'), ('viswanath', 'Viswanath'), ('shiva_ganesh', 'Shiva Ganesh'), ('anshu_kumar', 'Anshu Kumar'), ('aishwarya', 'Aishwarya Shetty'), ('sajid', 'Sajid Khurshid'), ('prasanna', 'Prasanna Akash'), ('jithin', 'Jithin Peter'), ('nitesh', 'Nitesh Tiwari')], default='saravana_kumar', max_length=500, verbose_name='Applied To')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('description', models.CharField(db_index=True, default='Description & Responsibilities Assigned', max_length=400, verbose_name='Notes')),
                ('leave_status', models.CharField(choices=[('n/a', 'N/A'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='N/A', max_length=30, verbose_name='Leave Status')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='users.user')),
            ],
            options={
                'db_table': 'leave',
            },
        ),
    ]
