# Generated by Django 4.1.4 on 2022-12-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leave_employee_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='employee_ids',
            new_name='employee_id',
        ),
    ]
