# Generated by Django 3.2.4 on 2022-05-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reviewed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of Reviewed')),
                ('critical_total', models.IntegerField(blank=True, null=True, verbose_name='Critical Score')),
                ('general_total', models.IntegerField(blank=True, null=True, verbose_name='General Score')),
                ('error_total', models.IntegerField(blank=True, null=True, verbose_name='Total Errors')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to='users.user')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_communication', to='tasks.task')),
            ],
            options={
                'db_table': 'communication',
            },
        ),
    ]
